name: StaffChat
version: ${project.version}
main: me.evasive.staffchat.StaffChat
softdepend: [PlaceholderAPI]
api-version: 1.15
commands:
  sc:
    description: Staff chat.
  staffchat:
    description: StaffChat admin.